# @Author: JerryLinLinLin
# @Date:   2022-06-16 01:11:55
# @Last Modified by:   JerryLinLinLin
# @Last Modified time: 2022-06-25 16:22:16
# This workflow will build rule sets with python script

name: Build

on:
  [push,pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi
    - name: Run rule validation
      run: |
        python scripts/validate_rules.py --path rules
    - name: Merge rule sets
      run: |
        python scripts/merge_rules.py --path rules --output output
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Huorong APT Rules
        path: output/*json
